kyeong8139/2024_Algorithm_Study

baekjoon/Sooyeon/퇴사_14501.java

[baekjoon-14501] 퇴사

---

baekjoon/Sooyeon/컴백홈_1189.java
baekjoon/Sooyeon/퇴사_14501.java

[baekjoon-sooyeon] 조수연

---

baekjoon/yoonji/퇴사_14501.java

[baekjoon-yoonji] 퇴사_14501

---

baekjoon/doeun/퇴사_14501.java

[baekjoon-doeun]14501 퇴사

---

baekjoon/bokyeong/컴백홈_1189.java

R, C, K의 최댓값이 크지 않아서 dfs로 풀어보았습니다!

[baekjoon-kyeong] 컴백 홈_1189

---

baekjoon/Heajun/주식_11501.java
baekjoon/Heajun/컴백홈_1189.java

[baekjoon-heajun] 컴백홈_1189

---

baekjoon/sangyong/주식_11501.java
baekjoon/sangyong/컴백홈_1189.java
baekjoon/sangyong/행렬_1080.java

[baekjoon-11501] 주식

---

baekjoon/bokyeong/주식_11501.java

완전탐색으로 구현했습니다
정렬 후 이진탐색으로 구현했으면 시간이 줄어들지는 판단해봐야할거같아요

[beakjoon-kyeong] 주식_11501

---

baekjoon/Seonghyeuk/컴백홈_1189.java

[baekjoon-1189] 컴백 홈

---

baekjoon/bokyeong/쿼드트리_1992.java
baekjoon/bokyeong/행렬_1080.java

이것이.. 그리디가 맞나요? 그리디 개념이 약해서 그리디적인 접근을 한지는 잘 모르겠네여
----
pull request 닫는거 깜박하고 쿼드트리 올렸네요..ㅎㅎㅎ 같이 봐주십셔

[baekjoon-kyeong] 행렬_1080 + 쿼드트리_1992

---

baekjoon/bokyeong/하노이탑_1914.java

어제 전공자반 강의를 들을 때 재귀를 구현할거면
1. 함수의 정의 (역할)
2. 매개변수
3. 종료시점
에 주의해서 설계해야한다고 하셔서 그 부분을 떠올리며 설계해봣습니다!

[baekjoon-kyeong] 하노이탑_1914

---

baekjoon/Seonghyeuk/하노이탑_1914.java

[baekjoon-seonghyeuk] 하노이탑_1914

---

baekjoon/bokyeong/N과M(1)_15649.java

[baekjoon-kyeong] N과M(1)_15649

---

baekjoon/yebeen/N과M_15649.java
baekjoon/yebeen/연산자끼워넣기_14888.java
baekjoon/yebeen/주식_11501.java
baekjoon/yebeen/컴백홈_1189.java
baekjoon/yebeen/쿼드트리_1992.java
baekjoon/yebeen/하노이탑_1914.java
baekjoon/yebeen/행렬_1080.java

연산자 끼워넣기 풀어보았습니다..
재귀로 받아서 계속 result값을 갱신해주었고, min값과 max값을 전역변수로 넣고 계속 비교해주면서 값을 받아서 main문의 가장 마지막 부분에서 출력했습니당

[baekjoon - yebeen] 연산자 끼워넣기 - 14888

---

baekjoon/Seonghyeuk/N과M_15649.java
baekjoon/Seonghyeuk/경로찾기2.java

[baekjoon-seonghyeuk]N과M(1)_15649

[baekjoon-seonghyeuk]N과M(1)_15649

---

baekjoon/bokyeong/연산자끼워넣기_14888.java

완탐말고 다른 방법이 있는지는 모르겠지만 
사전에 구상하면서 생각해보니
N이 11까지니까 calcurator 함수는 최대 N-1 10까지인데
for문을 length4로 도니까 4^10 = 2 ^ 10 ^ 2 = 100만 정도로 되겟더라구여 ^^

[baekjoon-kyeong] 연산자끼워넣기_14888

---

baekjoon/bokyeong/dfs와bfs_1260.java
baekjoon/bokyeong/경로찾기_11403.java

[baekjoon-kyeong] 경로찾기_11403

---

baekjoon/bokyeong/숨바꼭질_1697.java

빠른 시간이 키워드였는데 설계 자체를 잘못해서 헤멨내요 ㅠㅠㅠ

[beakjoon-kyeong] 숨바꼭질_1697.java

---

baekjoon/Seonghyeuk/안전영역.java
baekjoon/Seonghyeuk/연산자끼워넣기.java

[baekjoon-seonghyeuk] 안전영역_2468&연산자_끼워넣기_14888

[baekjoon-seonghyeuk] 안전영역_2468&연산자_끼워넣기_14888

---

baekjoon/bokyeong/계단오르기_2579.java

dp를 효율적으로 짜는 방법은 아직 어렵네요 다른 분들의 코드를 기다립니다

[baekjoon-kyeong] 계단오르기_2579.java

---

baekjoon/Seonghyeuk/계단오르기2.java

[beakjoon-hyeuk] 계단오르기_2579

---

baekjoon/연속합_1912.java

https://kyeong8139.tistory.com/13
이거는 예전에 풀었던 방법인데 이상한 풀이 궁금하면 참고하세요~

[baekjoon-kyeong] 연속합_1912.java

---

baekjoon/Seonghyeuk/연속합.java

[baekjoon-seonghyeuk] 연속합_1912

[baekjoon-seonghyeuk] 연속합_1912

---

baekjoon/Seonghyeuk/시험감독.java

[beakjoon-hyeuk] 시험감독_13458

---

baekjoon/bokyeong/스타트와링크_14889.java

nCr 조합을 뽑아서 점수차를 구했습니다.
조합을 뽑을 때는 nextPermutation이 시간이 덜 걸린다고 해서 활용해봤습니다

[beakjoon-kyeong] 스타트와링크_14889.java

---

baekjoon/Seonghyeuk/스타트와링크.java

[beakjoon-hyeuk] 스타트와링크_14889

---

baekjoon/bokyeong/톱니바퀴_14891.java

newGear로 안하고 idx하나의 값을 저장해둔 다음 하나씩 옮겼으면 될거같은데 라이브 쉬는시간에 풀다보니 마음이 급했습니다..

[baekjoon-kyeong]톱니바퀴_14891.java

---

baekjoon/bokyeong/14503_로봇청소기.java

[baekjoon-kyeong]14503_로봇청소기.java

---

baekjoon/Seonghyeuk/톱니바퀴.java
baekjoon/Seonghyeuk/파이프옮기기1.java

[beakjoon-hyeuk] 파이프옮기기1_17070&톱니바퀴_14891

[beakjoon-hyeuk] 파이프옮기기1_17070&톱니바퀴_14891

---

baekjoon/bokyeong/게리맨더링_17471.java

깔끔하진 않지만.. 풀었다는데에 만족합니다.
1. 입력값을 바탕으로 그래프 생성
2. 구역을 나눌 수 있는 모든 케이스 생성 (getSection)
3. 연결되어있는지 검사(getAns) 후 연결되어있으면 차의 최소값 구함

[beakjoon-kyeong]게리맨더링_17471.java

---

baekjoon/Heajun/N과M_2.java
baekjoon/Heajun/N과M_4.java
baekjoon/Heajun/마법사상어_21610.java
baekjoon/Heajun/배열돌리기4_17406.java

[baekjoon-heajun]마법사상어_21610

---

baekjoon/bokyeong/야구_17281.java

아직 퀵정렬이나 병합정렬을 못하다보니... 삽입정렬 부분에서 시간이 오래 걸렸을거같네요

[beakjoon-kyeong] 야구_17281.java

---

baekjoon/Seonghyeuk/N과M5.java
baekjoon/Seonghyeuk/N과M8.java

[beakjoon-hyeuk] N과M5_15654&N과M8_15657.java

[beakjoon-hyeuk] N과M5_15654&N과M8_15657.java

---

baekjoon/Seonghyeuk/가장긴증가하는부분수열.java
baekjoon/Seonghyeuk/트리의부모찾기3.java

[beakjoon-hyeuk] 가장긴증가하는부분수열_11053&트리의부모찾기_11725.java

[beakjoon-hyeuk] 가장긴증가하는부분수열_11053&트리의부모찾기_11725.java

---

baekjoon/Seonghyeuk/AtoB.java
baekjoon/Seonghyeuk/RGB거리2.java

[beakjoon-hyeuk]16953 A→B&&1149 RGB거리

[beakjoon-hyeuk]16953 A→B&&1149 RGB거리

---

baekjoon/Seonghyeuk/거짓말.java
baekjoon/Seonghyeuk/곱셈.java

[beakjoon-hyeuk]1043 거짓말&&1629 곱셈

[beakjoon-hyeuk]1043 거짓말&&1629 곱셈

---

baekjoon/Seonghyeuk/정수삼각형2.java
baekjoon/Seonghyeuk/특정한최단경로.java

[beakjoon-hyeuk]1932 정수삼각형&&1504특정한최단경로

[beakjoon-hyeuk]1932 정수삼각형&&1504특정한최단경로

---

baekjoon/Seonghyeuk/스티커.java
baekjoon/Seonghyeuk/트리의지름.java

[beakjoon-hyeuk] 스티커_9465&트리의지름_1967.java

[beakjoon-hyeuk] 스티커_9465&트리의지름_1967.java

---

baekjoon/Seonghyeuk/bj11660구간합구하기5_2.java
baekjoon/Seonghyeuk/bj1987알파벳.java

[beakjoon-hyeuk] bj1987알파벳&bj11660구간합구하기5_2.java

[beakjoon-hyeuk] bj1987알파벳&bj11660구간합구하기5_2.java

---

baekjoon/Seonghyeuk/내려가기.java
baekjoon/Seonghyeuk/문자열폭발_9935.java

[beakjoon-hyeuk]9935 문자열폭발&&2096 내려가기

[beakjoon-hyeuk]9935 문자열폭발&&2096 내려가기

---

baekjoon/Seonghyeuk/평범한배낭_12865.java
baekjoon/Seonghyeuk/행렬제곱_10830.java

[beakjoon-hyeuk] 평범한배낭_12865&행렬제곱_10830.java

[beakjoon-hyeuk] 평범한배낭_12865&행렬제곱_10830.java

---

baekjoon/Seonghyeuk/가장긴바이토닉부분수열_11054.java
baekjoon/Seonghyeuk/숨바꼭질3_13549.java

[beakjoon-hyeuk] 가장긴바이토닉수열_11054&숨바꼭질3_13549.java

[beakjoon-hyeuk] 가장긴바이토닉수열_11054&숨바꼭질3_13549.java

---

baekjoon/Seonghyeuk/치킨배달_15686.java
baekjoon/Seonghyeuk/플로이드_11404.java

[beakjoon-hyeuk] 치킨배달_15686&&플로이드_11404

[beakjoon-hyeuk] 치킨배달_15686&&플로이드_11404

---

baekjoon/피보나치수6_11444.java

[beakjoon-hyeuk] 피보나치수6_11444.java

[beakjoon-hyeuk] 피보나치수6_11444.java

---

baekjoon/Seonghyeuk/아기상어_16236.java
baekjoon/Seonghyeuk/연구소_14502.java

[beakjoon-hyeuk] 연구소_14502&&아기상어_16236.java

[beakjoon-hyeuk] 연구소_14502&&아기상어_16236.java

---

baekjoon/Seonghyeuk/서강그라운드_14938.java

[beakjoon-hyeuk] 서강그라운드_14938.java

[beakjoon-hyeuk] 서강그라운드_14938.java

---

baekjoon/Seonghyeuk/최소비용구하기2_11779.java

[beakjoon-hyeuk] 최소비용구하기2_11779.java

[beakjoon-hyeuk] 최소비용구하기2_11779.java

---

baekjoon/Seonghyeuk/bj20058_마법사상어와파이어스톰.java

[baekjoon_20058] 마법사상어와파이어스톰

---

baekjoon/Seonghyeuk/pg_단어변환.java

[programmers] 단어 변환

---

baekjoon/Seonghyeuk/bj7682_틱택토.java

[beakjoon-hyeuk] bj7682_틱택토

---

baekjoon/Seonghyeuk/pg_입국심사.java
pg_입국심사.java

[programmers-hyeuk] 입국심사

---

baekjoon/Seonghyeuk/bj2110_공유기설치.java

[beakjoon-hyeuk] bj2110_공유기설치

---

softeer/SeongHyeuk/sf6252_슈퍼컴퓨터클러스터.java
softeer/SeongHyeuk/sf6257_통근버스출발순서검증하기.java

[softeer-hyeuk] 6252슈퍼컴퓨터클러스터&6257통근버스출발순서검증하기

[softeer-hyeuk] 6252슈퍼컴퓨터클러스터&6257통근버스출발순서검증하기

---

baekjoon/Seonghyeuk/bj2073_수도배관공사.java

[beakjoon-hyeuk] 수도배관공사_2073.java

[beakjoon-hyeuk] 수도배관공사_2073.java

---

baekjoon/Seonghyeuk/ZOAC.java

[beakjoon-hyeuk] ZOAC_16719.java

[beakjoon-hyeuk] ZOAC_16719.java

---

programmers/SeongHyeuk/pg_삼각달팽이.java

[Programmers-hyeuk] 삼각 달팽이

---

programmers/SeongHyeuk/pg_조이스틱.java

[Programmers-hyeuk] 조이스틱

---

baekjoon/Seonghyeuk/bj15685_드래곤커브.java

[beakjoon-hyeuk] bj15685_드래곤커브.java

[beakjoon-hyeuk] bj15685_드래곤커브.java

---

programmers/SeongHyeuk/pg_더맵게.java

[Programmers-hyeuk] 더맵게

---

programmers/SeongHyeuk/pg_멀쩡한사각형.java

[Programmers-hyeuk] 멀쩡한사각형

---

programmers/pg_124나라의숫자.java

[Programmers-hyeuk] 124나라의숫자

---

baekjoon/Seonghyeuk/bj14500테트로미노.java

[beakjoon-hyeuk] bj14500테트로미노.java

[beakjoon-hyeuk] bj14500테트로미노.java

---

programmers/SeongHyeuk/pg_도넛과막대그래프.java

[Programmers-hyeuk] 도넛과막대그래프
